### ISSUE TITLE
CUDA error when running scPoli

### ISSUE THREAD

**Issue by DzvinkaYarish** [theislab/scarches#153]
Hi!

I'm trying to run the example notebook for scPoli, scpoli_surgery_pipeline.ipynb, with pancreas data. The model trains without errors when running on CPU. However, when I run it on GPU, I get the following error :

RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

The full trace:

![image](https://user-images.githubusercontent.com/17462781/208476197-8de9d9e1-7f1b-4e5e-9c41-74af0c46eb37.png)

Reducing batch size didn't solve the issue.
I'm using python3.8 with torch 1.13 and cuda 11.4

Any help would be greatly appreciated!

**Comment by cdedonno** [comment]
Hi, I am sorry you're having this issue. I have never encountered it during my work, it could be some issue with package versions. I have an environment with `cudatoolkit=11.3.1` and `torch=1.12.1` and everything seems to work fine. Can you try with these versions and report back? Then I can investigate more on what the issue might be.

**Comment by DzvinkaYarish** [comment]
I used the versions you specified and it solved the issue. Thanks!
